export const content: string;
export const hero: string;
export const large: string;
export const navigation: string;
export const navigationAction: string;
export const navigationContainer: string;
export const navigationList: string;
export const primary: string;
export const step2: string;
